Searchbar
DSVAG/Currency-exchanger pull request #10
Opened 2020-09-14 16:09 UTC by DSVAG

2020-09-15 07:33 UTC, MaximPestryakov commented on app/src/main/java/com/dsvag/currencyexchanger/data/utils/KeyBoardUtils.kt
> +            by lazy { getSystemService(context, InputMethodManager::class.java)!! }
У тебя опять зависимость создается внутри - вынеси в конструктор
```suggestion
class KeyBoardUtils(
    private val inputMethodManager: InputMethodManager,
) {
    private val TAG = KeyBoardUtils::class.simpleName
```

2020-09-15 07:52 UTC, MaximPestryakov commented on app/src/main/java/com/dsvag/currencyexchanger/data/adapters/CoinAdapter.kt
>          notifyDataSetChanged()
У тебя так анимация пропадает. Можно вместо `notifyDataSetChanged` и `notifyItemInserted` вызывать только `notifyItemRemoved`

2020-09-15 12:10 UTC, DSVAG commented on app/src/main/java/com/dsvag/currencyexchanger/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
Без этого не работает

2020-09-16 10:42 UTC, MaximPestryakov requested changes

2020-09-16 10:42 UTC, MaximPestryakov commented on app/src/main/java/com/dsvag/currencyexchanger/data/adapters/CoinAdapter.kt
> +                        .showKeyBoard(view)
Почему опять сам создаешь? Можно прокинуть через конструкторы: `CoinAdapter -> CoinViewHolder`

2020-09-16 10:42 UTC, MaximPestryakov commented on app/src/main/java/com/dsvag/currencyexchanger/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
Да, я тупанул. Короче `debounce` по-умолчанию переключается на другой поток. Тут либо оставить твой `observeOn`, либо сказать, чтобы `debounce` работал на главном потоке (и мне кажется так лучше):
```suggestion
            .debounce(300, TimeUnit.MILLISECONDS, AndroidSchedulers.mainThread())
```

То же самое нужно сделать со вторым `debounce`-ом, который у тебя есть

2020-09-16 11:12 UTC, DSVAG commented on app/src/main/java/com/dsvag/currencyexchanger/ui/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
в адаптере который?

2020-09-16 16:28 UTC, MaximPestryakov requested changes

2020-09-16 16:28 UTC, MaximPestryakov commented on app/build.gradle
> +        dataBinding true
Это зачем?
```suggestion
```

2020-09-16 16:28 UTC, MaximPestryakov commented on app/src/main/java/com/dsvag/currencyexchanger/ui/MainActivity.kt
> +    private val adapter = CoinAdapter(keyBoardUtils)
Теперь тут нужно `by lazy`, а иначе падает

2020-09-16 16:39 UTC, MaximPestryakov approved these changes

2020-09-16 16:40 UTC, merged